myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.input, name='home'),
    path('input', views.input, name='input'),
    path('submit', views.response, name='response'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect
import myapp.recipe_gcp
import myapp.trans
import myapp.picture
import csv
import datetime

# Create your views here.
def input(request):
    # GETリクエストの処理: 初期フォームを表示
    return render(request, 'myapp/input.html')

@csrf_protect
def response(request):
    # POSTリクエストの処理: フォームデータを変数に格納
    textbox1_value = request.POST.get('textboxBudget')
    textbox2_value = request.POST.get('textboxCommand')
    print(textbox1_value)
    print(textbox2_value)

    # ここで変数の値を使って何かする
    if textbox1_value == None:
        # 何かしらの処理。例えばデフォルト値を設定するなど。
        textbox1_value = "2000 円"

    if textbox2_value == None:
        # 何かしらの処理。例えばデフォルト値を設定するなど。
        textbox2_value = "春の季節をイメージした花束を、食卓に飾りたいです。花だけでなく、葉も入れた花束で、落ち着いた大人な雰囲気の花束にしてください。"

    print(textbox1_value)
    print(textbox2_value)

    csv_data = myapp.recipe_gcp.think_flower_recipe(textbox1_value, textbox2_value, datetime.datetime.today().strftime("%Y/%m/%d"))
    lines = csv_data.splitlines()
    reader = csv.reader(lines)
    parsed_csv = list(reader)  # パースされたCSVデータをリストに変換

    # 1行1列のみかどうかを判定
    if len(parsed_csv) == 1 and len(parsed_csv[0]) == 1:
        sorry_image_url = myapp.picture.generate_sorry_image()
        return render(request, 'myapp/sorry.html', {'message': parsed_csv[0][0], 'image_url': sorry_image_url})


    # 画像生成に投げるCSV
    # 次のような文字列
    #------------インプット------------
    #カーネーション(白),200,3,600
    #カーネーション(赤),200,1,200
    #カーネーション(黄),200,1,200
    #------------翻訳テスト------------
    #Carnation (white),3
    #Carnation (red),1
    #Carnation (yellow),1
    image_recipe_csv = myapp.trans.trans_csv_text(csv_data)

    image_url = myapp.picture.generate_final_prompt_and_create_image(image_recipe_csv)

    # 合計額が間違っている可能性があるため再計算をする
    for row in parsed_csv:
        unit_price = int(row[1])  # 単価
        quantity = int(row[2])    # 数量
        total_price = unit_price * quantity  # 合計額の計算
        row[3] = str(total_price)  # 計算した合計額をリストに戻す

    # 合計金額を計算
    total_amount = sum(int(row[3]) for row in parsed_csv)

    # テンプレートにデータを渡す
    context = {
        'textbox1_value': textbox1_value,
        'textbox2_value': textbox2_value,
        'data': parsed_csv,
        'image_url': image_url,
        'total_amount': total_amount,
    }
    return render(request, 'myapp/response.html', context)

    # # テンプレートにデータを渡す
    # context = {'data': parsed_csv}
    # return render(request, 'myapp/response.html', {
    #     'textbox2_value': context,
    #     'image_url': image_url,
    # })

myapp/templates/myapp/home.html
<!DOCTYPE html>
<html>
<head>
    <title>My Django App</title>
</head>
<body>
    <h1>Welcome to My Django App!</h1>
</body>
</html>

myapp/templates/myapp/input.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>花レシピ</title>
    <style>
        .title-background {
            background-color: #f9f9f9; /* タイトルの背景色をボディと同じに */
            padding: 20px;
            margin-bottom: 20px;
            text-align: center;
        }

        body {
            font-family: 'Meiryo', sans-serif;
            background-color: #f9f9f9; /* ベースの背景色 */
            color: #333;
            margin: 0; /* 余白のリセット */
            padding: 0; /* パディングのリセット */
            font-size: 18px;
        }

        h1 {
            color: #333; /* タイトルのテキスト色をソフトな色合いに */
            margin: 0;
            font-size: 2em;
        }

        .description p {
            color: #333;
            font-size: 1.2em; /* テキストのサイズ */
            text-align: center; /* テキストを中央揃えに */
            margin: 20px 0; /* 上下の余白 */
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            max-width: 500px;
            margin: auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 700;
            color: #4a766e;
            font-size: 1em; /* ラベルのフォントサイズ、bodyのフォントサイズに合わせて調整 */
        }

        input[type="text"],
        textarea {
            font-family: 'Meiryo', sans-serif;
            font-size: 1em; /* 入力フィールドのフォントサイズ、bodyのフォントサイズに合わせて調整 */
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4a766e; /* 初期背景色 */
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            font-weight: 700;
            text-transform: uppercase;
            transition: opacity 0.5s ease; /* 透明度のトランジションを設定 */
            background-image: none; /* ホバー前は背景画像なし */
            opacity: 1; /* 初期状態では背景画像を表示しない */
        }

        button:hover, button:focus {
            background-size: 100% auto; /* 画像の横幅がボタンの横幅に合わせて調整される */
            background-position: center; /* 画像をボタンの中央に配置 */
            background-repeat: no-repeat; /* 画像が繰り返されないように設定 */
            opacity: 0.7; /* ホバー時に背景画像を徐々に表示 */
        }

        a {
            display: inline-block;
            color: #4a766e;
            text-decoration: none;
            margin-top: 20px;
            font-size: 1em; /* リンクのフォントサイズ、bodyのフォントサイズに合わせて調整 */
        }

        a:hover {
            text-decoration: underline;
        }

        footer {
            background-color: #f9f9f9; /* フッターの背景色をボディと同じに */
            color: #333; /* フッターテキストの色を調整 */
            text-align: center;
            padding: 10px 0;
            position: fixed;
            bottom: 0;
            width: 100%;
            left: 0; /* フッターの左側の余白を修正 */
        }

        footer p {
            margin: 0;
            font-size: 0.8em;
        }

        /* レスポンシブデザイン */
        @media (max-width: 600px) {
            form {
                width: 100%;
                padding: 15px;
            }

            h1 {
                font-size: 1.5em; /* モバイルデバイス用にh1のフォントサイズを大きく */
            }
        }
    </style>
</head>
<body>
    <div class="title-background">
        <h1>花のレシピを作りましょう</h1>
    </div>

    <div class="description">
        <p>花で毎日に彩りを加えましょう。今日からあなたもフラワーコーディネーター。</p>
    </div>

    <form method="post" action="{% url 'myapp:response' %}">
        {% csrf_token %}
        <label for="textboxBudget">予算:</label>
        <input type="text" id="textboxBudget" name="textboxBudget" placeholder="2000 円">
        <div id="budgetError" style="color: red;"></div>
        
        <label for="textboxCommand">花のイメージを自由に書いてください:</label>
        <textarea id="textboxCommand" name="textboxCommand" rows="12" placeholder="春の季節をイメージした花束を、食卓に飾りたいです。&#10;花だけでなく、葉も入れた花束で、落ち着いた大人な雰囲気の花束にしてください。"></textarea>

        <button type="submit" onmouseover="this.style.backgroundImage='url({% static 'myapp/images/flower.webp' %})'" onmouseout="this.style.backgroundImage='none'">レシピを生成</button>

    </form>

    <footer>
        <p>© 2024 花のレシピ</p>
    </footer>

    <script>
        // 予算入力フィールドの値が変更されたときのイベントリスナーを設定
        document.getElementById('textboxBudget').addEventListener('input', function(e) {
            var input = e.target.value;
            var message = '';

            // 数字のみの入力を検証
            if (!input.match(/^\d+$/)) {
                message = '予算は数字のみで入力してください。';
            }
            document.getElementById('budgetError').textContent = message;
        });

        // 予算入力フィールドからフォーカスが外れたときのイベントリスナーを設定
        document.getElementById('textboxBudget').addEventListener('blur', function(e) {
            var input = e.target.value;

            // 既に「円」が追加されているか、または入力が空か数字以外でないかをチェック
            if (!input.endsWith('円') && input !== '' && !isNaN(input)) {
                e.target.value = `${input} 円`;
            }
        });
    </script>
</body>
</html>

myapp/templates/myapp/response.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>花レシピ</title>
    <style>
        .title-background {
            background-color: #f9f9f9; /* タイトルの背景色をボディと同じに */
            padding: 20px;
            margin-bottom: 20px;
            text-align: center;
        }

        body {
            font-family: 'Meiryo', sans-serif;
            background-color: #f9f9f9; /* ベースの背景色 */
            color: #333;
            margin: 0; /* 余白のリセット */
            padding: 0; /* パディングのリセット */
            font-size: 18px;
        }

        h1 {
            color: #333; /* タイトルのテキスト色をソフトな色合いに */
            margin: 0;
            font-size: 2em;
        }

        .description p {
            color: #333;
            font-size: 1.2em; /* テキストのサイズ */
            text-align: center; /* テキストを中央揃えに */
            margin: 20px 0; /* 上下の余白 */
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            max-width: 500px;
            margin: auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 700;
            color: #4a766e;
            font-size: 1em; /* ラベルのフォントサイズ、bodyのフォントサイズに合わせて調整 */
        }

        input[type="text"],
        textarea {
            font-family: 'Meiryo', sans-serif;
            font-size: 1em; /* 入力フィールドのフォントサイズ、bodyのフォントサイズに合わせて調整 */
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4a766e; /* 初期背景色 */
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            font-weight: 700;
            text-transform: uppercase;
            transition: opacity 0.5s ease; /* 透明度のトランジションを設定 */
            background-image: none; /* ホバー前は背景画像なし */
            opacity: 1; /* 初期状態では背景画像を表示しない */
        }

        button:hover, button:focus {
            background-size: 100% auto; /* 画像の横幅がボタンの横幅に合わせて調整される */
            background-position: center; /* 画像をボタンの中央に配置 */
            background-repeat: no-repeat; /* 画像が繰り返されないように設定 */
            opacity: 0.7; /* ホバー時に背景画像を徐々に表示 */
        }

        a {
            display: inline-block;
            color: #4a766e;
            text-decoration: none;
            margin-top: 20px;
            font-size: 1em; /* リンクのフォントサイズ、bodyのフォントサイズに合わせて調整 */
        }

        a:hover {
            text-decoration: underline;
        }

        footer {
            background-color: #f9f9f9; /* フッターの背景色をボディと同じに */
            color: #333; /* フッターテキストの色を調整 */
            text-align: center;
            padding: 10px 0;
            position: fixed;
            bottom: 0;
            width: 100%;
            left: 0; /* フッターの左側の余白を修正 */
        }

        footer p {
            margin: 0;
            font-size: 0.8em;
        }

        table {
            width: 80%; /* テーブルの幅 */
            margin: 20px auto; /* 中央配置 */
            border-collapse: collapse; /* セルのボーダーを結合 */
        }

        th, td {
            padding: 8px; /* セルのパディング */
            text-align: center; /* テキストを中央揃えに */
            border: 1px solid #ccc; /* セルのボーダー */
        }

        th {
            background-color: #4a766e; /* ヘッダーの背景色 */
            color: white; /* ヘッダーのテキスト色 */
        }

        tr:hover {
            background-color: #f5f5f5; /* 行にホバーした時の背景色 */
        }

        img {
            opacity: 0.8; /* 透明度を調整 */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* 影のサイズと色を調整 */
            border-radius: 10px; /* 角の丸みの大きさを調整 */
        }

        .button-container {
            text-align: center; /* テキストの中央揃えを適用 */
        }

        .button-container span {
            padding: 10px 15px;
            background-color: #4a766e; /* ボタンの背景色 */
            color: white; /* ボタンのテキスト色 */
            border: none; /* ボーダーを除去 */
            border-radius: 4px; /* 角を丸く */
            cursor: pointer; /* ホバー時にカーソルをポインターに */
            font-size: 16px; /* フォントサイズ */
        }

        .button-container span:hover {
            background-color: #3a656d; /* ホバー時の背景色 */
        }

        /* レスポンシブデザイン */
        @media (max-width: 600px) {
            form {
                width: 100%;
                padding: 15px;
            }

            h1 {
                font-size: 1.5em; /* モバイルデバイス用にh1のフォントサイズを大きく */
            }
        }
    </style>
</head>
<body>
    <div class="title-background">
        <h1>あなたの花のレシピはこちら</h1>
    </div>

    <div class="description">
        <p>予算 {{ textbox1_value }} でこのようなお花はどうでしょうか。</p>
    </div>

    <form>
        <!-- ここにテーブルを表示 -->
        <table border="1">
            <thead>
                <tr>
                    <th>品名</th>
                    <th>単価</th>
                    <th>数量</th>
                    <th>合計</th>
                </tr>
            </thead>
            <tbody>
                {% for row in data %}
                <tr>
                    {% for cell in row %}
                    <td>{{ cell }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="3">合計金額</td>
                    <td>{{ total_amount }}</td>
                </tr>
            </tbody>
        </table>

        <!-- 画像の表示 -->
        <img src="{{ image_url }}" alt="花のレシピ画像" width="512">

        <div class="button-container">
            <a href="{% url 'myapp:input' %}">
                <span>トップページに戻る</span>
            </a>
        </div>
    </form>

</body>
</html>

myapp/templates/myapp/sorry.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>花レシピ</title>
    <style>
        .title-background {
            background-color: #f9f9f9; /* タイトルの背景色をボディと同じに */
            padding: 20px;
            margin-bottom: 20px;
            text-align: center;
        }

        body {
            font-family: 'Meiryo', sans-serif;
            background-color: #f9f9f9; /* ベースの背景色 */
            color: #333;
            margin: 0; /* 余白のリセット */
            padding: 0; /* パディングのリセット */
            font-size: 18px;
        }

        h1 {
            color: #333; /* タイトルのテキスト色をソフトな色合いに */
            margin: 0;
            font-size: 2em;
        }

        .description p {
            color: #333;
            font-size: 1.2em; /* テキストのサイズ */
            text-align: center; /* テキストを中央揃えに */
            margin: 20px 0; /* 上下の余白 */
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            max-width: 500px;
            margin: auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 700;
            color: #4a766e;
            font-size: 1em; /* ラベルのフォントサイズ、bodyのフォントサイズに合わせて調整 */
        }

        input[type="text"],
        textarea {
            font-family: 'Meiryo', sans-serif;
            font-size: 1em; /* 入力フィールドのフォントサイズ、bodyのフォントサイズに合わせて調整 */
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4a766e; /* 初期背景色 */
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            font-weight: 700;
            text-transform: uppercase;
            transition: opacity 0.5s ease; /* 透明度のトランジションを設定 */
            background-image: none; /* ホバー前は背景画像なし */
            opacity: 1; /* 初期状態では背景画像を表示しない */
        }

        button:hover, button:focus {
            background-size: 100% auto; /* 画像の横幅がボタンの横幅に合わせて調整される */
            background-position: center; /* 画像をボタンの中央に配置 */
            background-repeat: no-repeat; /* 画像が繰り返されないように設定 */
            opacity: 0.7; /* ホバー時に背景画像を徐々に表示 */
        }

        a {
            display: inline-block;
            color: #4a766e;
            text-decoration: none;
            margin-top: 20px;
            font-size: 1em; /* リンクのフォントサイズ、bodyのフォントサイズに合わせて調整 */
        }

        a:hover {
            text-decoration: underline;
        }

        footer {
            background-color: #f9f9f9; /* フッターの背景色をボディと同じに */
            color: #333; /* フッターテキストの色を調整 */
            text-align: center;
            padding: 10px 0;
            position: fixed;
            bottom: 0;
            width: 100%;
            left: 0; /* フッターの左側の余白を修正 */
        }

        footer p {
            margin: 0;
            font-size: 0.8em;
        }

        table {
            width: 80%; /* テーブルの幅 */
            margin: 20px auto; /* 中央配置 */
            border-collapse: collapse; /* セルのボーダーを結合 */
        }

        th, td {
            padding: 8px; /* セルのパディング */
            text-align: center; /* テキストを中央揃えに */
            border: 1px solid #ccc; /* セルのボーダー */
        }

        th {
            background-color: #4a766e; /* ヘッダーの背景色 */
            color: white; /* ヘッダーのテキスト色 */
        }

        tr:hover {
            background-color: #f5f5f5; /* 行にホバーした時の背景色 */
        }

        img {
            opacity: 0.8; /* 透明度を調整 */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* 影のサイズと色を調整 */
            border-radius: 10px; /* 角の丸みの大きさを調整 */
        }

        .button-container {
            text-align: center; /* テキストの中央揃えを適用 */
        }

        .button-container span {
            padding: 10px 15px;
            background-color: #4a766e; /* ボタンの背景色 */
            color: white; /* ボタンのテキスト色 */
            border: none; /* ボーダーを除去 */
            border-radius: 4px; /* 角を丸く */
            cursor: pointer; /* ホバー時にカーソルをポインターに */
            font-size: 16px; /* フォントサイズ */
        }

        .button-container span:hover {
            background-color: #3a656d; /* ホバー時の背景色 */
        }

        /* レスポンシブデザイン */
        @media (max-width: 600px) {
            form {
                width: 100%;
                padding: 15px;
            }

            h1 {
                font-size: 1.5em; /* モバイルデバイス用にh1のフォントサイズを大きく */
            }
        }
    </style>
</head>
<body>
    <div class="title-background">
        <h1>申し訳ありません</h1>
    </div>

    <div class="description">
        <p>{{ message }}</p>
    </div>

    <form>
        <!-- 画像の表示 -->
        <img src="{{ image_url }}" alt="すみませんの画像" width="512">
        
        <div class="button-container">
            <a href="{% url 'myapp:input' %}">
                <span>トップページに戻る</span>
            </a>
        </div>
    </form>
</body>
</html>